version: '3.8'

services:
        app:
                image: lassad2/lassaddev:1.0.0
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "8089:8089"
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stationSki?createDatabaseIfNotExist=true
                        SPRING_DATASOURCE_USERNAME: root
                        SPRING_DATASOURCE_PASSWORD: ''
                        SPRING_JPA_HIBERNATE_DDL_AUTO: none
                        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
                depends_on:
                        - db

        db:
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: ''
                        MYSQL_DATABASE: stationSki
                volumes:
                        - db_data:/var/lib/mysql
                ports:
                        - "3306:3306"
                healthcheck:
                        test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1"]
                        interval: 10s
                        retries: 5
                        start_period: 30s  # Optional: Adds a delay before health check starts
                        timeout: 10s       # Optional: Sets a timeout for the health check

volumes:
        db_data:
