version: '3.8'
services:
  app:
    build: .
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestion_ski
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh mysql:3306 -- ./start-app.sh"]

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gestion_ski
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
